//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualLeaf
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int AnnualLeaveID { get; set; }
        public Nullable<double> FK_EmpAnnualLeave { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public Nullable<double> AnnualLeaveTotal { get; set; }
        public Nullable<double> AnnualLeaveUsed { get; set; }
        public Nullable<double> AnnualLeaveRemain { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
