//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
        public int CompID { get; set; }
        public string CompCode { get; set; }
        public string CompName { get; set; }
        public string CompAddr { get; set; }
        public string CompPhone { get; set; }
        public string CompFax { get; set; }
        public string CompTaxNum { get; set; }
        public string CompWeb { get; set; }
        public string CompEmail { get; set; }
    }
}
