//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int ContractID { get; set; }
        public string ContractCode { get; set; }
        public string ContractName { get; set; }
        public string ContractNum { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<double> ContractExp { get; set; }
        public Nullable<decimal> ContractSalary { get; set; }
        public string ContractDesc { get; set; }
        public string ContractNode { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
