//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int DegreeID { get; set; }
        public string DegreeCode { get; set; }
        public string DegreeName { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
        public string DegreePlace { get; set; }
        public string DegreeDept { get; set; }
        public string DegreeMajor { get; set; }
        public Nullable<System.DateTime> DegreeDate { get; set; }
        public string DegreeRank { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public Nullable<int> AAOrder { get; set; }
    }
}
