//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ethnic
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public Nullable<int> AAOrder { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
        public int EthnicID { get; set; }
        public string EthnicCode { get; set; }
        public string EthnicName { get; set; }
        public string EthnicDesc { get; set; }
    }
}
