//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleSub
    {
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_RoleID { get; set; }
        public int RoleSubID { get; set; }
        public string RoleDesc { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
