//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string RoleCode { get; set; }
        public Nullable<int> RoleChild { get; set; }
        public string RoleUrl { get; set; }
        public string RoleIcon { get; set; }
        public string RoleBadgeVariant { get; set; }
        public string RoleBadgeText { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
