//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int SalaryID { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public string FK_EmpName { get; set; }
        public Nullable<decimal> SalaryBasic { get; set; }
        public Nullable<decimal> SalaryReward { get; set; }
        public Nullable<decimal> SalarySupSalary { get; set; }
        public Nullable<decimal> SalaryTotal { get; set; }
        public Nullable<double> SalaryWorkDay { get; set; }
        public Nullable<decimal> SalaryActTotal { get; set; }
        public Nullable<decimal> SalaryContract { get; set; }
        public Nullable<decimal> SalaryKPCPEmp { get; set; }
        public Nullable<decimal> SalaryBHXHEmp { get; set; }
        public Nullable<decimal> SalaryBHYTEmp { get; set; }
        public Nullable<decimal> SalaryBHTNEmp { get; set; }
        public Nullable<decimal> SalaryKPCPComp { get; set; }
        public Nullable<decimal> SalaryBHXHComp { get; set; }
        public Nullable<decimal> SalaryBHYTComp { get; set; }
        public Nullable<decimal> SalaryBHTNComp { get; set; }
        public Nullable<decimal> SalaryAdvance { get; set; }
        public Nullable<decimal> SalaryFinal { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
