//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int SetID { get; set; }
        public string SetSalaryType { get; set; }
        public Nullable<double> SetKPCDComp { get; set; }
        public Nullable<double> SetBHXHComp { get; set; }
        public Nullable<double> SetBHYTComp { get; set; }
        public Nullable<double> SetBHTNComp { get; set; }
        public Nullable<double> SetKPCDEmp { get; set; }
        public Nullable<double> SetBHXHEmp { get; set; }
        public Nullable<double> SetBHYTEmp { get; set; }
        public Nullable<double> SetBHTNEmp { get; set; }
        public Nullable<double> SetTimekeep { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
