//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_SER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public string AACreate { get; set; }
        public Nullable<System.DateTime> AACreateDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<bool> AASelection { get; set; }
        public int TimeSheetID { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public string FK_EmpTimeWrkCode { get; set; }
        public string FK_EmpCode { get; set; }
        public string FK_EmpName { get; set; }
        public Nullable<System.DateTime> TimeSheetDate { get; set; }
        public Nullable<int> TimeSheetDay { get; set; }
        public string TimeSheetShift { get; set; }
        public Nullable<System.DateTime> TimeSheetCheckIn { get; set; }
        public Nullable<System.DateTime> TimeSheetCheckOut { get; set; }
        public Nullable<double> TimeSheetHourTotal { get; set; }
        public Nullable<double> TimeSheetWork { get; set; }
        public Nullable<double> TimeSheetLate { get; set; }
        public Nullable<double> TimeSheetOutSoon { get; set; }
        public Nullable<double> TimeSheetOutLate { get; set; }
        public string TimeSheetSign { get; set; }
        public Nullable<System.Guid> AAGuid { get; set; }
    }
}
